# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "t-aksh@microsoft.com"
      git config --global user.name "Akash Sharma"
      $contents = Get-Content -Raw -Path CreateWebApp/Config.json | ConvertFrom-Json
      $ARMtemplate = Get-Content -Raw -Path CreateWebApp/ADFTutorialARM.json | ConvertFrom-Json
      $ARMParameters = Get-Content -Raw -Path CreateWebApp/ADFTutorialARM-Parameters.json | ConvertFrom-Json

      $DataFactoryPipeline = @"
      {
        "name": "PushedPipeline",
        "type": "Microsoft.DataFactory/factories/pipelines"
      }
      "@
      
      $contents[0].resources[0].EndPoint = "Changed EndPoint"
      $contents | ConvertTo-Json | set-content CreateWebApp/Config.json
      #$ARMtemplate.resources += (ConvertFrom-Json -InputObject $DataFactoryPipeline)

      New-AzResourceGroupDeployment -Name MyARMDeployment -ResourceGroupName Intern_Akash_RG -TemplateFile CreateWebApp/ADFTutorialARM.json -TemplateParameterFile CreateWebApp/ADFTutorialARM-Parameters.json
